services:
    security.authentication.factory.cosign_sso:
        class:  SAS\IRAD\CosignSSOBundle\DependencyInjection\Security\Factory\CosignSSOFactory
        tags:
            - { name: security.listener.factory }